-- MySQL Script generated by MySQL Workbench
-- Mon Apr 26 06:52:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ppsync
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ppsync` ;

-- -----------------------------------------------------
-- Schema ppsync
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ppsync` DEFAULT CHARACTER SET utf8 ;
USE `ppsync` ;

-- -----------------------------------------------------
-- Table `ppsync`.`user_tel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`user_tel` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`user_tel` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tel` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_tel_tel_index` (`tel` ASC) VISIBLE,
  INDEX `user_tel_user_id_foreign` (`user_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`status` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ppsync`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`profile` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `profile_status_id_foreign` (`status_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`user_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`user_status` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`user_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ppsync`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`persona` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`persona` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `tel` VARCHAR(255) NOT NULL,
  `document_number` VARCHAR(255) NOT NULL,
  `document_type_id` INT NOT NULL,
  `create_at` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ppsync`.`document_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`document_type` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`document_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `document_type_description_index` (`description` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`user` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `per_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  `user_card` INT NOT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `document_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_email_unique` (`email` ASC) VISIBLE,
  INDEX `user_profile_id_foreign` (`profile_id` ASC) VISIBLE,
  INDEX `user_status_id_foreign` (`status_id` ASC) VISIBLE,
  INDEX `user_per_id_foreign` (`per_id` ASC) VISIBLE,
  INDEX `user_document_type_id_foreign` (`document_type_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`request_motive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`request_motive` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`request_motive` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ppsync`.`request_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`request_status` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`request_status` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ppsync`.`request_status_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`request_status_history` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`request_status_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `status_request_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `create_at` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `request_status_history_user_id_foreign` (`user_id` ASC) VISIBLE,
  INDEX `request_status_history_status_request_id_foreign` (`status_request_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`request` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`request` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `form_id` INT NOT NULL,
  `passport_number` VARCHAR(255) NULL DEFAULT NULL,
  `civil_right` ENUM('') NOT NULL,
  `nif` VARCHAR(255) NOT NULL,
  `request_date` DATETIME NOT NULL,
  `request_motive_id` INT NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `new_passport_number` VARCHAR(255) NOT NULL,
  `status` ENUM('') NOT NULL,
  `filler_user_id` INT NOT NULL,
  `suggestion` VARCHAR(255) NOT NULL,
  `create_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `request_firstname_index` (`firstName` ASC) VISIBLE,
  INDEX `request_lastname_index` (`lastName` ASC) VISIBLE,
  INDEX `request_form_id_index` (`form_id` ASC) VISIBLE,
  INDEX `request_passport_number_index` (`passport_number` ASC) VISIBLE,
  INDEX `request_request_date_index` (`request_date` ASC) VISIBLE,
  INDEX `request_phone_index` (`phone` ASC) VISIBLE,
  INDEX `request_status_index` (`status` ASC) VISIBLE,
  INDEX `request_filler_user_id_index` (`filler_user_id` ASC) VISIBLE,
  INDEX `request_request_motive_id_foreign` (`request_motive_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`request_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`request_history` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`request_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `request_id` INT NOT NULL,
  `create_at` DATETIME NOT NULL,
  `form_id` INT NOT NULL,
  `passport_number` VARCHAR(255) NOT NULL,
  `request_date` DATETIME NOT NULL,
  `civil_right` ENUM('') NOT NULL,
  `nif` VARCHAR(255) NOT NULL,
  `request_motive_id` INT NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `new_passport_number` INT NOT NULL,
  `status` ENUM('') NOT NULL,
  `user_id` INT NOT NULL,
  `filler_user_id` INT NOT NULL,
  `createAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `request_history_request_id_foreign` (`request_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`menu_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`menu_type` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`menu_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ppsync`.`menu_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`menu_profile` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`menu_profile` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `profile_id` INT NOT NULL,
  `menu_type_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `menu_profile_menu_type_id_foreign` (`menu_type_id` ASC) VISIBLE,
  INDEX `menu_profile_profile_id_foreign` (`profile_id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `ppsync`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppsync`.`log` ;

CREATE TABLE IF NOT EXISTS `ppsync`.`log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `logout_at` DATETIME NOT NULL,
  `create_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `log_user_id_foreign` (`user_id` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
