@hostname = localhost
@port = 1337
@host = {{hostname}}:{{port}}
@contentType = application/json

# @name login
POST http://{{host}}/auth/local
content-type: application/json

{
    "identifier": "carteasy@gmail.com",
    "password": "develop"
}
###

@authToken = {{login.response.body.jwt}}

###
GET http://{{host}}/resquest-motives/
Authorization: Bearer {{authToken}}

###
GET http://{{host}}/resquest-motives?_limit=2
Authorization: Bearer {{authToken}}
###
GET  http://{{host}}/resquest-motives?_sort=description
Authorization: Bearer {{authToken}}

###
GET  http://{{host}}/resquest-motives?_sort=id:desc
Authorization: Bearer {{authToken}}
###

GET http://{{host}}/resquest-motives/count
Authorization: Bearer {{authToken}}

###
POST http://{{host}}/resquest-motives/
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "description": "Changement Renseignements",
    "state": "active"
}


# auth
###
GET http://localhost:1337/users/count
###

###
GET http://localhost:1337/request-motives?_sort=id:desc
Authorization: Bearer {{authToken}}
###

GET http://localhost:1337/request-motives/count
Authorization: Bearer {{authToken}}

###
DELETE http://localhost:1337/request-motives/29
Authorization: Bearer {{authToken}}
###
PUT http://localhost:1337/request-motives/29
Authorization: Bearer {{authToken}}

###
PUT http://{{host}}/resquest-motives/4
Authorization: Bearer {{authToken}}
content-type: application/json

{
    "description": "Changement Renseignements01",
    "state": "active"
}
